services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    environment:
      - SERVER_PORT=8081
      - TZ=Asia/Taipei
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Taipei
    networks:
      - family_net

networks:
  family_net:
    name: family_shared_network